import Head from 'next/head';
import { ReactElement } from 'react';
import { Intro, Top3Roof, Top3PlayList } from './main/components';
import { TabMenuLayout } from '@/components';

const MainPage = () => {
  return (
    <>
      <Head>
        <title>MusicPlayer: Top3</title>
        <meta name="description" content="Generated by hoon" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <article className="h-full">
        <Intro />
        <Top3Roof />
        <Top3PlayList />
      </article>
    </>
  );
};

MainPage.getLayout = (page: ReactElement) => {
  return <TabMenuLayout>{page}</TabMenuLayout>;
};

export default MainPage;
