import Head from 'next/head';
import { ReactElement } from 'react';
import { useRouter } from 'next/router';
import { RootLayout } from '@/components';

import { BackButton } from './components';

import * as Styled from './styled';
import { usePlayMusic } from './hooks';

const PlayPage = () => {
  const { query } = useRouter();
  const { data: music } = usePlayMusic(query.id as string);

  return (
    <>
      <Head>
        <title>MusicPlayer: Play</title>
        <meta name="description" content="Generated by hoon" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <Styled.Container>
        <BackButton />
      </Styled.Container>
    </>
  );
};

PlayPage.getLayout = (page: ReactElement) => {
  return <RootLayout>{page}</RootLayout>;
};

export default PlayPage;
