import Head from 'next/head';
import { ReactElement } from 'react';
import { useRouter } from 'next/router';

import { RootLayout } from '@/components';

const PlayPage = () => {
  const router = useRouter();
  console.log(router.query);
  return (
    <>
      <Head>
        <title>MusicPlayer: Play</title>
        <meta name="description" content="Generated by hoon" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>

      <div>init play page</div>
    </>
  );
};

PlayPage.getLayout = (page: ReactElement) => {
  return <RootLayout>{page}</RootLayout>;
};

export default PlayPage;
