import Head from 'next/head';

const Home = () => {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by hoon" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
			</Head>

			<h1 className="text-3xl font-bold underline">MusicPlayer</h1>
		</>
	);
};

export default Home;
